### ISSUE TITLE
Folder naming static vs public

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#105]
I am making some tutorials. [Sveltejs/template](https://github.com/sveltejs/template) uses `public` for its static folder. We use `static`.

I would like to keep names aligned as much as possible with sveltejs template for beginners to make it easier to switch over.

Any reason to have it called `static`?

**Comment by rixo** [comment]
Because, it contains static assets that are copied to a build/dist directory that will eventually be publicly exposed by a web server; as opposed to the public directory that is directly being exposed by the HTTP server in Svelte's default template.

As a side note, I've only been met with resistance and some advice to sanitize my directories structure by seasoned web developers, with what is done by the official Svelte template -- that is output generated files in the same directory that also contains static assets sources. It also goes against the patterns I've come to establish along my own career as a web developer.

I keep this structure for my hot template for the reason you've cited, that is alignment with Svelte official template. I also see the simplicity value of doing so for beginners, as you mention in #106. This file structure is the simplest possible, and requires less prior experience to understand. But for my own projects, I'm ready to drop it as soon as I have more meaningful static assets that an `index.html` and 2 images.

I think that Routify starter's structure is more aligned with real world projects, while Svelte template is aimed at beginners and hobbyists. Which I also find reasonable, because experienced developers have the hindsight to adjust things to how they work and scale best, while neofits, by definition, lack the knowledge necessary to understand a more involved setup. And so, if you present them with something complicated, they're just lost and give up. While with something simple, they can progressively build upon it.

All in all, I think we currently only have an "advanced" starter, that fits well with experienced developers. I think Routify as an ecosystem would benefit from a simpler starter, in addition to this one, that would be better suited for people that are in the process of grasping many concepts at once. This would essentially be a copy of ~~Svelte's official~~ my hot template with routing added -- no SSR, no code splitting, just simplicity you can build upon once you've wrapped your head around it.

Any volunteer?

**Comment by jakobrosenberg** [comment]
Closed due to inactivity.
