### ISSUE TITLE
Routify doesn't catch changes in global.css

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#107]
If I add a rule to global.css, save, and refresh the page, it doesn't work.

Steps to reproduce

```
git clone https://github.com/Wolfr/hn-clone-svelte-be.git
npm i
npm run dev
```

Go to global.css. Add a rule like

```
* {
  background: yellow;
}
```

Observe that no change happens.

**Comment by Wolfr** [comment]
I was editing the global.css file in the wrong folder. Duh. Sorry for logging all these issues in Routify when it's just me being tired.

**Comment by rixo** [comment]
If you additionally resave `main.js` and reload, the change in `global.css` is taken into account.

The reason is the way Rollup's watch works. It doesn't watch a full directory or all the files matching a given pattern, it watches only you entry points and the file you `import` into them (and the things you `import` into them...).

Since `global.css` is not imported, but only referenced (by URL) from the HTML files, it only gets copied to the dist directory by the Rollup copy plugin when something Rollup is watching changes.

Doesn't happen in Svelte official template 'cause statics and public/dist are the same thing. Duh. #105 

Either we go back to stone age like Svelte's template, or over-engineered distopia by adding a CSS plugin to Rollup and properly `import`ing `global.css` from `App.svelte` instead of merely referencing it from `index.html`. Hard call.

Another option would be to drop `global.css` entirely from the starter, and let people figure how to handle their `.css` with Rollup on their own. Otherwise, maybe our current "advanced" starter should go with `rollup-plugin-postcss`, and we further need a simpler starter where public and dist are the same, as also noted in #106.

**Comment by Wolfr** [comment]
Whew. I thought this was just a bug 😅

**Comment by rixo** [comment]
You won't be alone in thinking like this. CSS, particularly global, not working / refreshing as expected is one of the most frequent complaint I get in my hot templates, and I've also seen reports to this effect on the official templates (although mostly PEBCAK in this case).

In keeping with @jakobrosenberg's "sane defaults" / "zero-config startup" philosophy, I think we'd better address this. At the very least, we drop `global.css` instead of having something partly working... Which could lead people to lose time debugging, the more they'll trust us, the more time they'll lose because they won't consider the problem can come from us. Not a very considerate thing to do to our users.

This issue belongs in the starter template though. Routify doesn't do CSS.

**Comment by Wolfr** [comment]
I am organising a code-along this Friday, with 20+ people coming to join me in building a hacker news clone using Svelte and Routify.

Last night I was making it based on Routify starter and regularly had to start-stop my compiler. If there's one way to give a bad impression of maturity... maybe I should fix it in a separate fork and have them download that to begin with.

**Comment by jakobrosenberg** [comment]
@Wolfr I'm going off topic here, but is there a reason you don't use ``<style>`` tags in ``.svelte`` files? Not a suggestion. Just curiosity.

``global.css`` is a bit of a static file to me. Like an asset. If it were to be used as a dynamic source file instead, it would make more sense to me to import it in ``main.js``.

In general code should act as one would expect, but what happens when people have different expectations or even wrong expectations. I think the best way to handle these scenarios, is by showing a correct approach.

IMO the current structure reflects what can be expected of Rollup. Files in the static folder are static and changing them won't cause an update. As often seen in other projects, we could create a ``src/assets`` folder for css/scss and import it in ``App.svelte``. This keeps things simple in the sense that ``src`` is for dynamic content.

**Comment by Wolfr** [comment]
Using style tags in Svelte files works for small demos and small projects.

The Svelte provided CSS scoping is super nice for exceptions to the general rule in bigger projects and for quick coding of experiments.

The reason to have a separate CSS architecture is

1. to be able to use SCSS in its full capacitiy (that is a system where theme variables can traverse through in full) without hacky workarounds
2. to be able to use established conventions such as BEM and ITCSS (see Harry Roberts's work on this which is absolutely great - it is difficult to explain in a sentence)
3. to be able to use the exact same codebase CSS-wise, regardless of the Javascript framework (we have plenty of projects that provide a CSS base for projects in Angular, PHP and React at the same time)

For example, we use the exact same SCSS in our Wordpress version as in our current Svelte version. There's some definite business benefits in maintaining proper CSS as a separate “thing”.
