### ISSUE TITLE
Join us on #Discord

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#116]
Because a lot of people look here in issues - a general announcement. Need help? Have feedback? 

Join us: https://discord.gg/5M3FE68

**Comment by jakobrosenberg** [comment]
Closed as the link is in the README now.

**Comment by jakobrosenberg** [comment]
On second thought. This might be good for people looking for support.

**Comment by Grsmto** [comment]
Hey, FYI the Discord invitation link is expired!

Edit: https://discord.com/invite/ntKJD5B

**Comment by jakobrosenberg** [comment]
Thanks @Grsmto. I just tried it in incognito window with no issue. Checking the link in Discord also shows it to have no experiation.

Could you try it again, just to verify this wasn't a glitch in Discord's code?

**Comment by Wolfr** [comment]
I get it as well. In any case, here's a new link that should work:
https://discord.gg/YJTj2Nf

**Comment by ghostdevv** [comment]
Closing because it will still say pinned if closed, tag if the link expires!

**Comment by MrPixel1** [comment]
I hope you don't mind me pointing out that people look into issues here, because they understand what Discord is: a restrictive, malicious and privacy invasive web service and proprietary product.

I myself tend to avoid "open source" projects which attempt to lure unsuspecting users and to make them give up their privacy.

That said, it would be amazing if an alternative could be provided:

Specifically speaking, this could be a [Matrix space](https://matrix.org/docs/chat_basics/public-rooms/#spaces) where channels are [bridged with Discord channels](https://matrix.org/ecosystem/bridges/discord). A similar solution could be possible [with IRC](https://github.com/OpenTTD/dibridge) as well.

That way, malicious software would not be imposed on those interested in interacting with this community, and it would allow those who were coerced to use Discord to break free from the restrictive platform.

Moreover, a bridge solution would not force any of the oppressed users to move away from the restrictive platform. It would remain their choice.

**Comment by jakobrosenberg** [comment]
@MrPixel1 is that an ad for Matrix or are you a user of Routify with a concern about our community?
