### ISSUE TITLE
Rollup build process hangs

### ISSUE THREAD

**Issue by khuongduybui** [roxiness/routify#145]
So, this one I am sure is valid!

I'm running latest stable version of `rollup` and `routify`.
Currently I have `routify({}),` under `plugins: []` in my `rollup.config.js`.

When I run `rollup --config` (without any additional arguments or environment variables) the process hangs after creating all bundle files.

I set `NODE_ENV=test` before running the command and got the same issue.

I currently have to hot-patch my installation of `routify` with

```diff
diff --git a/node_modules/@sveltech/routify/plugins/rollup.js b/node_modules/@sveltech/routify/plugins/rollup.js
index ad48921..66f5a88 100644
--- a/node_modules/@sveltech/routify/plugins/rollup.js
+++ b/node_modules/@sveltech/routify/plugins/rollup.js
@@ -67,6 +67,15 @@ module.exports = function svelteFileRouter(inputOptions) {
       await waitIdle()
     },
 
+    // build-only API
+    // needed for the production build to shut up properly (otherwise the process
+    // will hang because of dangling file watchers)
+    ...(!process.env.ROLLUP_WATCH && {
+      async buildEnd() {
+        return close()
+      },
+    }),
+
     // test-only API
     ...(process.env.NODE_ENV === 'test' && {
       // needed for the test runner to shut up properly (otherwise the process

```

**Comment by jakobrosenberg** [comment]
Anyone for a PR? @khuongduybui  @rixo

**Comment by rixo** [comment]
Wait, it seems like there's something else to it... `close` closes the watcher, otherwise it just does nothing (noop). And, indeed, an active watcher will hang the process. But if calling `close` helps your case, that means there's an active watcher. But there shouldn't be active watchers for single runs...

@khuongduybui [here](https://github.com/sveltech/routify/blob/eaa0b2779d199712d135859c3b991917c8b02e44/lib/services/interface.js#L56), can you check if `watch` comes truthy, for single run (aka build), in your case? And if so, can you try to trace why?

**Comment by khuongduybui** [comment]
`watch` is set to `process.env.ROLLUP_WATCH` so it's not truthy (otherwise my additional code block would have had no effects)

**Comment by khuongduybui** [comment]
I think the problem is because the `watch` option has no effect per https://github.com/sveltech/routify/blob/e0cb27ad0c842bd1d60b16c0742198a9b67dc0c0/lib/services/interface.js#L56

**Comment by khuongduybui** [comment]
Let me try renaming https://github.com/sveltech/routify/blob/bac37cb2318bc1b0be9da2540d7e2f3bb468677b/plugins/rollup.js#L10 to `singleBuild` and see if it works

**Comment by khuongduybui** [comment]
Soooo that works, thanks @rixo for pointing it out. I updated my PR.
