### ISSUE TITLE
Thoughts, Opinions and Questions

### ISSUE THREAD

**Issue by alteredorange** [roxiness/routify#148]
Thanks for all the great work on this plugin! I just finished building a very small site with it: [https://quibi-is-doomed.web.app/](https://quibi-is-doomed.web.app). I'm a newbie, so just wanted to share my thoughts and experiences if you're interested.

I learned Sapper first, but couldn't really use Firebase firestore reliably, so I switched back to Svelte and found Routify. I really like how it has the same 1 file = 1 route. Here's some things I had to fiddle around with to figure out:

1. Why are there two config files (.json5 and yaml). It seems like some changes worked and some didn't, and I'm not sure if it reads one or both of them.

2. It might make sense to have `npm run dev` output to a separate folder, so your build files remain untouched, instead of getting deleted if you switch back to dev. Maybe `npm run build` could output to /public

3.  This might be a bug, but when building and hosting on Firebase, pages route to Fallback first, and then to the page, unless I'm clicking on a link. You can see what I mean by going to https://quibi-is-doomed.web.app/ and then typing in and going to /thanks.  It flashes the 404 page and then routes to /thanks. But from thanks, if you click on the title and go back to the homescreen, it doesn't route to the 404 first.

4. This might be a Firebase specific thing, but they insert a 404 page if your project doesn't have one. So i copied the _fallback.svelte into 404.svelte, which gets exported as 404.html. Might be nice to do this automatically. Not sure if that could also be behind issue number 3 above.

5. Documentation on the different build options is sparse. I'd love to help out if I can, I'm still fuzzy on what all the options do. It would also be great to have an export option like Sapper that generates everything for a static site, although it seems to pretty much do this anyway.

Thanks again for the great work!

**Comment by jakobrosenberg** [comment]
Thanks for the feedback @alteredorange 🙂

1) We want to get rid of the configs and instead use .env / environment variables. I can't remember the reasoning, if there was any, for including two. Youv can delete either or both.

 2) We have to consider the that a lot of people find the amount of files and folders daunting. You could use the included Rollup copy plugin to automatically copy the dist folder to a separate build folder when in production mode. That would save it from being overwritten. I've never had a use for a persistent build folder, but I'm curious about the use case.

3) You have a prerendered 404 page in place of the thanks page. You can see it here (in Chrome) ``view-source:https://quibi-is-doomed.web.app/thanks```. What happens is your browser fetches a prerendered 404 page, while downloading the app bundle in the background. Once the app bundle is loaded, it replaces the prerendered HTML. This should be the exact same content and cause no flickers, but for some reason your prerendered content is a 404. Do you have a repo you can share or do you have an idea as to what the reason could be?

4) A SPA should always be hosted with URL rewrites/404 redirects enabled to ensure it receives all unresolved requests. In other words, your host should forward all 404s to your app, not the other way around. I suspect this could be related to your 404 issues - though I'm still puzzled why the 404 is prerendered.

5) Apologies for the documentation, or lack thereof, on build options. There has been rapid development in this area over the last few weeks and just today did Netlify and Now help us come up with solutions for both platforms, so we can now integrate both in a much more transparent and complete fashion. (there's an early draft here https://routify-2020-f5nqbxe1q.now.sh/guide/production/overview )

**Comment by alteredorange** [comment]
Thanks for all the responses!  I probably set up the hosting wrong in Firebase, because I was trying to make it more just a static site. I wasn't sure how all the SPA stuff works :) I uploaded the project here to take a look if you want, although without the firebase config it might throw some errors: https://github.com/alteredorange/RoutifyStuff    As for the seperate folders for dev and build, when I was just going back and forth between building and dev, I pushed a dev upload to firebase, which re-wrote everything without any static pages, so the site was dead. Obviously there should be staging, etc. but for small local stuff, if you accidentally push out the build folder, it would be nice to have the last full build in there rather than an empty dev one.

**Comment by jakobrosenberg** [comment]
For safe deploys, the best approach is to have your build and deploy scripts run sub-sequentially. This can be done locally with an npm script like ``"build-deploy": "npm run build && npm run deploy:service"`` or it can be done with CI. A separate build folder would add complexity and if you forget to build before deploying, you're pushing old code instead of unoptimized code. The former being a Pandora's box of issues.

I cloned your project and noticed an error when rendering it in JSDOM ``TypeError: Cannot read property 'getElementById' of undefined``. I've posted an issue with JSDOM to find out if there's something that can be done about logging stack traces from the eval.

**Comment by alteredorange** [comment]
@jakobrosenberg I think that error is because firebase has to load first. Firebase hosting is kind of a mess, but I got most of it sorted! I've also been messing around with your Now deploy, because I just noticed Now even let's you do serverless functions! Which is awesome!  But it also brought up some more questions :)

1. Firebase needs an index.html to redirect everything back to. That was the issue I was having, because I was basically serving the static index.html that Routify exported, rather than a "blank" index.html with an "app" div to target. If I create my own index.html with an "app" div things worked as expected.

2. It looks like Now and Surge also use an index.html, and I'm guessing it's built during the "npm run deploy:now" command. I deployed a project just fine, but if I run that command again, it doesn't deploy it to production, only testing, with a "To deploy to production, run 'now --prod'. Except I can't run 'now --prod' because there is no now project, it looks like you're creating a hidden Now project and index and then getting rid of it?  

3. For me it would make sense to create a nowDeploy folder that holds your .now project settings (so you can change and upgrade things), and when you run the deploy now command, it rebuilds that folder without deleting what's in there, only changing the actual build files. That way, on the first deploy, it would create the basic index.html file, but on subsequent builds it would check and see it's already there and not delete it, so you could modify it with scripts and styles as needed. That way you could also add an /api folder, so you can use Now's serverless functions. I also noticed running the 'npm run deploy:now' doesn't completely wipe the /dist folder, but if you run 'npm run dev' again, everything gets wiped, so you couldn't add your own custom folders and index without it getting wiped.  Hopefully that makes sense, sorry if I'm thinking about this the completely wrong way!

4. I have noticed a few other projects work like the above, where they include a basic index.html and global.css, and then everything else gets removed/updated on build, except those two files.

5. I've been playing around with Routify a lot, and noticed that the process seems different from installing the starter template, and installing it separately.  Installing separately, when you run the "routify" command, it just builds the routes, and watched for new routes. When you install the starter template, running the same "routify" command will start routify and also run rollup. Might be worth having them both do the same thing, so that running the same command doesn't do different outputs.

6. One last thing :) So do the two config files do anything at the moment? If I delete them both, is there a place to change config options? Ok that's it for now, promise!

Sorry for all the long-windedness, this is probably all just due to my lack of experience! Thanks again for the help!

**Comment by alteredorange** [comment]
I've been playing around with Now, and I did manage to set it up from the root folder, just needed to change the presets:

In root of project I ran "now".

Left everything the same, except for auto-detect project settings (Svelte): N, then
Build Command: npm run build
Output Directory: dist
Development Command: npm run start

Seems to be working. Then I was able to add an API folder in the project root, which also worked! I think you'd even be able to use "now" defaults if the output was in /public rather than /dist to match Svelte conventions. That way you wouldn't need to maintain your own now script, you can just deploy by running "now" in project root.

**Comment by jakobrosenberg** [comment]
Hi @alteredorange 

2. To pass parameters through npm tasks, you have to add a `--`, so your command becomes ``npm run deploy:now -- --prod``. (Without the `--`, npm would think the argument is intended for npm.) You can setup custom deploy commands in package.json, ie. ``deploy:now:prod``.

3. The static folder contains templates for index.html (called ``__dynamic.html`` and ``__bundle.html``). In the current beta they're consolidated to just ``__index.html``. This is the folder you want to use for static files, like your index.html, css, serverless api functions.

4. I've only ever seen that pattern once. In the official Svelte template. I strongly advice against it or any other approach that mixes input and output in the same folder. With source, statics and distributables, you have a clear separation of concerns. 

5. Routify is just a router. It works with any bundler (Rollup, Webpack, Parcel, etc) and any server (Sirv, express, etc.) With the starter template we provide an opinionated, batteries-included approach for anyone to use as a base or study as an example.

6. IIRC the config file tells Routify to run Rollup once it's generated its routes (since you don't want to start your server with a missing routes.js). The 1.5 beta doesn't use the configs.


Adding ``Now`` to the root is an option, but not one I'm keen on as long as it requires adding vendor specific folders in the root.

EDIT:
You should come join us on Discord. I might be able to save you some time with what you're doing.

**Comment by alteredorange** [comment]
Got all of this sorted, going through and closing issues :) Thanks!
