### ISSUE TITLE
Difficulty understanding route priority

### ISSUE THREAD

**Issue by matthewrobb** [roxiness/routify#17]
Lets say you have the following files:
```
/pages/_fallback.svelte
/pages/[foo]/index.svelte
/pages/[foo]/_fallback.svelte
```
As I understand it these will map to the follow regex strings:
```
"^/"
"^/([^/]+)/index"
"^/([^/]+)/"
```
And here's what my intuition suggests about various input paths:
```sh
"/"        => /pages/_fallback.svelte
"/bar"     => /pages/[foo]/index.svelte
"/bar/baz" => /pages/[foo]/_fallback.svelte
```
So now what SHOULD happen if I delete `/pages/[foo]/index.svelte`? My intuition would suggest that `/pages/[foo]/_fallback.svelte` should be the match however currently it does not.

I am just curious what the intended mappings ought to be, I can open PR's to help fix bugs but I don't want to deviate from expected behavior.

**Comment by jakobrosenberg** [comment]
Hi @matthewrobb 

You need a trailing slash to achieve what you're looking for. ``/bar/" should give you the expected the result.

``/bar/`` is treated as a folder/module and it will look for ``/bar/index.svelte`` first and then ``/bar/_fallback.svelte``.
``/bar`` is treated as a file and it will look for ``/bar.svelte`` first and then ``/_fallback.svelte``

I have no preference for one type of mapping vs another. This just happens to be how the router resolves URLs with its current wiring. What you suggest would probably make more sense.

The problem is that ``/bar/_fallback.svelte`` matches ``^/bar/`` and not ``^bar``.
- If we strip the last last slash, ``/docker/images/1`` could fallback to ``/doc/_fallback.svelte/``.
- If we automatically suffix URLs with a ``/`` before mapping, Everything would go haywire.

The best option would probably be a preliminary check against a suffixed URL before trying the original.

**Comment by jakobrosenberg** [comment]
I'll have it implemented in the next beta. Hopefully out before the end of the day.

**Comment by matthewrobb** [comment]
@jakobrosenberg awesome! I did get route matching to work the way I was thinking, probably not in an ideal manor but you can check it out here https://github.com/matthewrobb/svelte-filerouter/tree/route-matching-fixes

**Comment by jakobrosenberg** [comment]
I fixed this in the last beta release. v1.4.1 beta. Would you see if it works as intended?

**Comment by matthewrobb** [comment]
I will try it out as soon as I can, thanks!

**Comment by matthewrobb** [comment]
After playing with the latest last night I found things working fairly well however there is an oddness:
**Page Component Files**
```sh
/pages/_fallback.svelte
/pages/[foo]/index.svelte
/pages/[foo]/bars/[bar].svelte
```
When navigating to `/foo/bars/bar` everything works as expected, however, it seems to be matching like a wildcard and thus `/foo/bars/bar/baz/etc` into infinity is hitting `/pages/[foo]/bars/[bar].svelte` where my natural assumption would be that it hit `/pages/_fallback.svelte`.

**Comment by matthewrobb** [comment]
If you have a param segment as a folder with an index you will get the correct behavior, if you use a single file to manage a param segment then you end up with inconsistent matching. I would assume regardless of file structure, expectations would be for `/foo/[bar].svelte` and `/foo/[bar]/index.svelte` to have the same consistency of matching.
