### ISSUE TITLE
Compiling as custom tag is not working

### ISSUE THREAD

**Issue by MrSrsen** [roxiness/routify#200]
I have use-case (micro-frontend) when I want to use entire application as custom tag in another application.

**bug description**

When I try to use Routify with Svelte `customElement: true` option I get warning:

> (!) Plugin svelte: No custom element 'tag' option was specified. To automatically register a custom element, specify a name with a hyphen in it, e.g. <svelte:options tag="my-thing"/>. To hide this warning, use <svelte:options tag={null}/>

but I have `<svelte:options tag="my-thing"/>` written in file `/src/App.svelte`.

So my question is... **Does Routify support compilation as custom tag element?**

**package.json**
```
"dependencies": {
    "@sveltech/routify": "^1.7.12",
    "svelte": "^3.20.1"
}
```

**Comment by jakobrosenberg** [comment]
I can't see why it shouldn't work, but it's not something we've considered.

**Comment by rixo** [comment]
I've been experimenting quite a bit with Svelte's custom elements lately and I'm very skeptical that this can be made to work nicely...

@MrSrsen Note that when you set `customElement: true` then Svelte expects _all your components_ that are involved in the bundle to be custom elements -- said otherwise, to have a `<svelte:options tag="..." />`.

Also, this means that you can't:

~~~html
<script>
  import Foo from './Foo.svelte'
</script>

<Foo />
~~~

It should be something like this instead:

~~~html
<script>
  import './Foo.svelte' // ensure the component is in the build
</script>

<my-foo-component />
~~~

Props are handled differently in customElement and normal mode too...

I was pretty unpsyched with those (and already had a full non-custom-element-oriented codebase...), so I also tried to render a _normal_ Svelte App component in shadow DOM myself instead. This kind of works, but then Svelte suffers some limitations (like transitions not working, in what I have identified) from being under shadow DOM (because normal Svelte runtime doesn't expect it).

Also, I don't think Routify is ready for this kind of encapsulation. It would need some kind of support for "scoped routing" or something. Although this part is probably worthwhile on its own, so it might make sense to do it, as an independent issue from custom elements support.

**Comment by Wolfr** [comment]
Huh? Why would you use a routing framework when the compile target is a custom element? You would normally only have a single route then.

**Comment by jakobrosenberg** [comment]
I stand corrected. This doesn't sound like something that's realistic for Routify.

**Comment by MrSrsen** [comment]
Thanks guys for the very helpful comments! Now I at least know where I stand and how I should continue my planning and work.

**Comment by jakobrosenberg** [comment]
I'm closing this issue, but feel free to continue the discussion.
