### ISSUE TITLE
Dynamic routes not working on nginx

### ISSUE THREAD

**Issue by lucasdall** [roxiness/routify#204]
Hi Guys, I hope everybody's doing well.

I'm using "@sveltech/routify": "^1.0.1-29" and I want to build the webapp in a static package and use Nginx to serve it. 

My webapp is already in production and I'm using "sirv" in that env. I don't know if the sirv is recommended to production envs and I want to change to nginx. 

The webapp is an eCommerce platform and I gonna dynamic URLs to access the details page of each product, ex:
www.mysite.com/product/productABC
www.mysite.com/product/productDFG
and so on...

Using sirv, everything is going fine but after some hours the webapp crash because of a corrupted bundle.js. It seems pretty odd because I don't why the bundle.js is rewritten during the execution.

When I use nginx to serve the static pkg generated, It does run pretty well but the only problem happens when I get the URL directly in the location on the web browser. What I get is that when a type the URL directly on the browser looks like the request was not in the svelte context.

Using nginx, if I have a link in my home page pointing to www.mysite.com/product/productABC it will work as expected. If I put the www.mysite.com/product/productABC directly in the browser, it doesn't work and I get a 404 error message.

Does anyone has passed through something similar to this?

My svelte version is: 3.16.7
@sveltech/routify": "^1.0.1-29

Thanks,
Lucas

**Comment by colinbate** [comment]
I'm fairly new to Routify, so I can't tell you how much has changed over the past couple months, but Routify is now on version 1.7 (with 1.8 coming soon I suspect). I'm not sure how much of your original issue is due to that. Sirv should be fine.

However, the issue you are seeing with Nginx is you need to redirect all requests to the main entry point of the application. Not sure what it was originally, `__app.html` or something perhaps. Or `index.html` You will need to look into the `try_files` directive for Nginx. Something like:

```
try_files $uri $uri/ /index.html;
```

**Comment by lucasdall** [comment]
Hey Colin,

Updating both dependencies (svelte and routfy) and using the **try_files** directive solves the issue and now I'm able to use nginx.

Thanks a lot, man!

**Comment by colinbate** [comment]
Glad it worked out.
