### ISSUE TITLE
async assigning a value to metatags doesn't work

### ISSUE THREAD

**Issue by Kneemund** [roxiness/routify#279]
**Bug Description**
Assigning a value to `metatags` inside of a function (e.g. a request callback) throws `Error: Function called outside component initialization`.

**Routify Version**
2.1.3 (latest)

**Example**
```TS
import { ready, metatags } from '@roxi/routify';
[...]

$: user = {};

axios.post([...]).then((res) => {
        user = res.data;
        metatags.title = "test";
        $ready();
});
```

**Comment by madeleineostoja** [comment]
I also hit this issue, fairly large use case with metadata coming from a CMS (for example).

**Comment by ghostdevv** [comment]
Is this still an issue @jakobrosenberg

**Comment by jakobrosenberg** [comment]
AFAIK yes.

**Comment by lamualfa** [comment]
@jakobrosenberg  

Please give a warning to [metatags](https://routify.dev/docs/metatags) section. for 2 days I tried to find the cause of this error. First time, I thought this error came from Vite. it turns out that the error comes from the `metatags` helper 😂.

https://github.com/vitejs/vite/pull/2435#issuecomment-798814008

I can make a PR to give the warning if you want. Let me know.

**Comment by ghostdevv** [comment]
I am confused what the linked comment is involved? Am I missing something? @lamualfa

**Comment by lamualfa** [comment]
@ghostdevv 

In First time when I get this Error, I think the problem came from Vite. Because of that, I try to find the solution about that error and I found the same problem It also happened in the svelte kit. 

One of the svelte kit contributor said that the error was caused by Vite. Then the error has been fixed in the latest PR made by the svelte kit contributor to the vite repository.

It's been 2 days since the PR was made the changes haven't been merged. Impatient, I tried to comment on the PR page (_That's the link I gave above_).

2 days later PR was merged and the latest version of vite was out. I rushed to get the version tested right away on my routify project. After updating, it turns out that the error still occurs.

I was really confused to find out what caused the error. In the end, I tried to dig deeper into the issues that exist in routify repository. And then Voila! I encountered this issue with the exact same case as mine.

I use `metatags` helper inside `.then` function.

**Comment by jakobrosenberg** [comment]
This has hopefully been fixed in `v2.16.0`.

For async metatags, use `$metatags` instead of `metatags`. This is somewhat experimental, so if you encounter any bugs, please let me know.

**Comment by lamualfa** [comment]
@jakobrosenberg Is `v2.16.0` has been released?

![image](https://user-images.githubusercontent.com/39755201/111602886-645e1200-8806-11eb-9655-6d55a8a21ccb.png)

<hr>

I have tried to use it in `v2.12.4`, but it keeps getting errors.

**`src/pages/test.svelte`**

```svelte
<script>
  import { onMount } from 'svelte';
  import { metatags } from '@roxi/routify';

  onMount(() => {
    new Promise((resolve) => setTimeout(resolve, 3000)).then(() => {
      $metatags.title = 'Hello world';
    });
  });
</script>

<h1>Hello world</h1>
```

**Error**

![image](https://user-images.githubusercontent.com/39755201/111602729-3aa4eb00-8806-11eb-9da6-71d26e1b84e2.png)

**Comment by jakobrosenberg** [comment]
@lamualfa https://www.npmjs.com/package/@roxi/routify/v/2.16.0

The store API has only been added in `2.16.0`, so it won't work before that.

**Comment by lamualfa** [comment]
@jakobrosenberg Oh ok. it looks like the NPM cache has just been updated. I am sorry 😅.

**Comment by lamualfa** [comment]
@jakobrosenberg Voila! now it's work in `v2.16.0`. Thank you very much @jakobrosenberg.

![image](https://user-images.githubusercontent.com/39755201/111603359-d8001f00-8806-11eb-8f42-58962444be49.png)

**Comment by jakobrosenberg** [comment]
Closing this for now then. 🙂
