### ISSUE TITLE
Magic is hard to debug

### ISSUE THREAD

**Issue by mathiasrw** [roxiness/routify#295]
Thank you for creating Routify. 

Input: I would love to see better debug messages from Routify, What is going on when compiling is like a black box and very hard to debug if the error message is not very exact.

Example: importing a nonexisting svelte file from a _layout will return no error but a blank screen. No info at all.

**Comment by jakobrosenberg** [comment]
Routify only compiles a `routes.js` which contains a map of routes -> components.

Since your issue is within a _layout file which Routify doesn't "touch", I'm guessing it's not directly related to Routify.

That said, I'm happy to add better debugging if this turns out to be Routify related of if there are other areas where we can improve debugging.

**Comment by mathiasrw** [comment]
Oh - My bad! I was sure the _layout file setup was a routify thing. Sorry about that.

**Comment by mathiasrw** [comment]
Hmm. The problem with the blank screen is not there when I remove `<!-- routify:options bundle=true -->` from the _layout file. Ill investigate more and make a bugreport if I find a simple way of reproducing this.

**Comment by jakobrosenberg** [comment]
Ah. Still don't think it's a Routify issue as such, but I'm getting curious now. Let me know what you find. 🙂
