### ISSUE TITLE
empty span element

### ISSUE THREAD

**Issue by timeshift92** [roxiness/routify#347]
**First rule of bug posting**
**There are no rules!**

#### With that out of the way, there are a few things that might help us help you faster. You pick and choose what you think is relevant.

**bug description**
hello, how can I remove this span ?

**package.json**
The script section or even just the script you're running.

**version**
"@roxi/routify": "^2.14.0",
"svelte": "^3.35.0",

**screenshot**
Sometimes they help. Extra points for good memes.
![image](https://user-images.githubusercontent.com/13614530/110246580-f9047c80-7f89-11eb-9bbb-32c10a8c7fe9.png)

**Comment by jakobrosenberg** [comment]
Since Svelte components aren't able to determine their parent DOM elements, `Router.svelte` inserts an empty span next to each page and layout component in order to determine their parent elements.

If this is an issue I'll see if I can remove it after the parent element is detected (this happens instantaneously).

**Comment by ghostdevv** [comment]
@timeshift92

**Comment by timeshift92** [comment]
thanks for the answer, I will fix it via css =)

**Comment by fbele** [comment]
> Since Svelte components aren't able to determine their parent DOM elements, `Router.svelte` inserts an empty span next to each page and layout component in order to determine their parent elements.
> 
> If this is an issue I'll see if I can remove it after the parent element is detected (this happens instantaneously).

I understand, it's probably a technical necessity.
However it doesn't really resolve the issue. As described in ticket [#352](https://github.com/roxiness/routify/issues/352#issue-837950608), there was the same source code used but with different results/behaviour
Why are the spans not appearing in the official example site, but they are when I'm compiling and running the exact same source code? What and where is the difference?

I would just like to know what to do in order to remove them?

Thanks.

**Comment by jakobrosenberg** [comment]
@fbele I'll look into removing them.

The reason they're not in the starter example on Vercel is most likely that the example hasn't been rebuilt since they were added.

**Comment by fbele** [comment]
> @fbele I'll look into removing them.
> 
> The reason they're not in the starter example on Vercel is most likely that the example hasn't been rebuilt since they were added.

Thank you for the swift reply. Okay, I understand.
I was convinced I was doing something wrong, therefore I was asking the question.
