### ISSUE TITLE
Capture whether event is a page “leave”

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#37]
It would be useful to me to be able to see when the user is trying to leave the page.

Notice that when you click a link to another nav item on this Games page: https://bestof2019.johanronsse.be/games you will have to wait for the transition of the slider component to run before the page is left.

I would like to intercept that animation call and check whether you are leaving the page, and then in case you are leaving the page disable that “out” transition.

As far as I know, Routify doesn't have any option to capture this, is this correct?

Any other ideas on how to solve this would be helpful, if it can be worked around that is also useful.

**Comment by jakobrosenberg** [comment]
Routify could definitely benefit from events. How to implement them is the question. I'd like global events for page changes and maybe events at the component level, but I wonder if these aren't already handled by Svelte's onDestroy() etc.

For your specific case, would local transitions do the trick? If not, I'll prioritize hooks/events.
https://svelte.dev/tutorial/local-transitions

**Comment by Wolfr** [comment]
Brilliant, simply adding `|local` to the transition does the trick. I didn't know about this.

**Comment by joelhickok** [comment]
I know this is closed, and I can open another issue of necessary, but I am trying to use the Svelte `onDestoy` lifecycle event to prevent the user from leaving the page if they decide they have "unsaved changes."  But, of course, it doesn't work since there is no way to cancel onDestroy (that I have figured out), and Svelte.js doesn't have additional lifecycle events like Vue 's `beforeDestroy` or Vue Router (see: Vue Router in-component `beforeRouteEnter`, `beforeRouteUpdate`, `beforeRouteLeave` at https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards)

This case is the traditional, "Are you sure you want to leave without saving your changes..." confirm prompt, but since the onDestroy method doesn't have the option to `return false` I cannot stop the page transition.  So, I would *love* to be able to do it on the Routify level instead.  Should I open an issue requesting page handler event helpers, that react to the window.location changes?

```html
<script>
  import {beforeRouteLeave} from '@sveltech/routify/runtime/helpers'
  
  // must return true to continue
  beforeRouteLeave((inRoute, outRoute) => {
    if (hasUnsavedChanges) {
        return confirm('Are you sure you want to leave without saving?')
    }
    return true
  })
</script>
```

**Comment by jakobrosenberg** [comment]
This is an excellent use case for events. 👍

This is the current flow when navigating to a new page.
1. A custom ``history.pushstate`` wrapper intercepts the call
2. The wrapper forwards the call to the original ``history.pushstate``
3. The wrapper dispatches a ``pushstate``, ``popstate`` or ``replacestate`` event.
4. The event is intercepted and updatePage() is called.

I assume you want to hook into step 1 and prevent not just the page update, but the url change.

On top of the list there, we also have Route.svelte which wraps around each layout and page. There are a few functions in here which rely on synchronized calls. Even though we don't have to map them now, but it's important to avoid "umbrella" events that cover these events, if we need fine grained events down the road.

Ideas for the event in question could be ``beforeUrlChange``, ``beforeRouteChange`` or ``beforePathChange``

@rixo what do you think of the example function?

**Comment by joelhickok** [comment]
Yes, preventing the path from changing is ideal...  essentially stopping the entire flow immediately because the user decided it was a good idea to remain on that page with the same url and any existing route params or query parameters.

`beforeRouteChange` seems appropriate...?

**Comment by jakobrosenberg** [comment]
As a temporary fix you can wrap the history.pushstate
<details>

```javascript
const _pushstate = history.pushstate
function history.pushstate(...params){
  ...
  if (condition) _pushstate(...params)
}
```
</details>

If it's not urgent, I'll try get around to it in the near future.

**Comment by jakobrosenberg** [comment]
Added in 1.0.1-52

```javascript
import { beforeUrlChange } from "@sveltech/routify";
  let editorIsDirty = false

  $beforeUrlChange((event, store) => {
  return !editorIsDirty
});
```

The hooks will automatically be removed when component is destroyed.

**Comment by joelhickok** [comment]
This seems to be working great.  Nice addition!
