### ISSUE TITLE
Q: Linking

### ISSUE THREAD

**Issue by tombroens** [roxiness/routify#46]
I enter a page at http://localhost:5000

I navigate with a `<a href="/org/1234">`' in my base layout to a component.

When I use a `<a href="structure">` to now go deeper in the hierarchy it strips the param (1234) from the resulting url. Is this normal behaviour? Hence I end up in: http://localhost:5000/org/structure in stead of http://localhost:5000/org/1234/structure

**Comment by jakobrosenberg** [comment]
This is the default behavior of browsers. It treats the last slash as the current folder and since you're navigating to a relative URL, that's the folder it will be looking in.

You can:
1. Make sure the URL has a trailing slash to denote that it's a folder.
2. Use an absolute URL
3. Use the $url helper.

I generally try to stay away from relative vanilla URLs as they change accordingly to your current location, often making them unreliable.

**Comment by tombroens** [comment]
Amazing thanks, I learned something here.
