### ISSUE TITLE
`routify-starter` could deserve not to be a fork of Svelte template

### ISSUE THREAD

**Issue by akauppi** [roxiness/routify#69]
Creating the issue here, since https://github.com/sveltech/routify-starter doesn't have Issues enabled.

>![image](https://user-images.githubusercontent.com/1297734/72984734-08a81c80-3ded-11ea-96a6-48fbbfb978e5.png)

The `routify-starter` repo is currently a fork off the main Svelte template. This causes some surprises for end users like me: since I had the Svelte repo forked, GitHub insists I cannot fork this one (it sees them as the same, as it should).

Breaking the fork would mean that `routify-starter` is essentially a different template than the Svelte base one. Which I think it is. It will make updating upstream changes (to Svelte template) more manual, but.. life is.

**Comment by rixo** [comment]
We've already discussed this with @jakobrosenberg and we both agree ([same problem](https://github.com/rixo/svelte-template) for me). This wasn't really done on purpose... It is expected that Routify starter will diverge more and more from Svelte's official template, and that changes will only be cherry picked and backported manually as they make sense for Routify. This point is relatively moot anyway, since repos that share the same git parent can be merged in one another, irrelevant of whether Github sees them as forks or not.

The real question though is: do you happen to know _how_ to do this?

As far as I know, the only way to unlink the fork would be to rename the existing template (to `sveltech/svelte-template`, I guess?) and create a whole new repository (on GH) for the starter. This has the drawback of losing all existing activity on the repo (issues, PRs, etc.). This still seems acceptable at this point, but maybe there is a better solution that we are not aware off? Maybe GH support can handle this? Any suggestion?

@jakobrosenberg Maybe we should just recreate the starter repository right now and be done with it. The more we wait, the more things we'll lose we do it...

**Comment by jakobrosenberg** [comment]
I wrote Github a while back to unfork it. Haven't heard from them. I say we rename the old one and create a new one in its place. Then eventually we can delete the old one when we feel confident we don't need the commit history.

**Comment by jakobrosenberg** [comment]
They've been unforked! Thanks for giving us that last nudge @akauppi.  Rixo has been dragging his feet on this one. ^^
