### ISSUE TITLE
Deciding whether to use `npx run routify` or the Rollup plugin

### ISSUE THREAD

**Issue by akauppi** [roxiness/routify#72]
I've installed `@sveltech/routify` 1.0.1-38 and have some bumps, getting to use it from `npx`:

```
$ npx routify --help
Cannot find module 'puppeteer'
Require stack:
- /Users/asko/Git/svg.rx.js-demo/node_modules/@sveltech/routify/lib/services/exporter.js
- /Users/asko/Git/svg.rx.js-demo/node_modules/@sveltech/routify/plugins/cli.js
```

That aside, what exactly would running `routify` do, as a build step?  I think this could be described [here](https://routify.now.sh/docs/config), to help people like me decide, whether we want to configure it via `package.json` (build file), or Rollup config.

I'm fairly knowledgable with JavaScript build frameworks, so hand holding not needed. I did not see the sources, just too busy I guess.

**Comment by jakobrosenberg** [comment]
That bug should have been fixed in that version. My mistake. I fixed it, but forgot to remove the import.

I'm admittedly far behind on the documentation, but at the current moment, it's a moving target and I'm not sure it's a good idea to document something that's still changing.

I pushed a new update. It should be working now.

As for how Routify builds, I'm gonna describe how it's working in my local code. I'll try push it in the near future.
``npm run build``
1. Routify first builds a bundle through Rollup (code-splitting by default)
2. Sirv hosts the site for a few seconds while Puppeteer saves the HTML from all static sites. (Anything without a ``/[prop]``)

This gives you prerendered routes for all static pages and then for the dynamic routes it falls back to the html entry point which servers the app as a SPA. For static pages, you still get a working SPA as it's inserted into the ``document.body`` once it's loaded.

I managed to deploy a site to Netlify earlier today with SSR, cache and prerendered pages. Worked like a charm, though SSR should only be used for search engines.

Sorry if I'm a bit all over the place.

**Comment by jakobrosenberg** [comment]
Just read the title again. Rollup or npx shouldn't matter. I would recommend a local install of Routify though.

**Comment by akauppi** [comment]
I can see it's moving - like it! 👍 

<strike>Would you still check the `ncp` dependency - likely needed but currently in `devDependencies`. With 1.0.1-39 I get:

```
$ npx routify --help
Cannot find module 'ncp'
Require stack:
- /Users/asko/Git/svg.rx.js-demo/node_modules/@sveltech/routify/lib/services/exporter.js
- /Users/asko/Git/svg.rx.js-demo/node_modules/@sveltech/routify/plugins/cli.js
```
</strike>

https://github.com/sveltech/routify/pull/76
