### ISSUE TITLE
Parameter route renders in place of “regular” sub route

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify#82]
I think I found a problem that might be related to the regex order problems we found before that is still in place in the last version `42`.

## How to reproduce

* Create a parameter route based on a folder and a file [folder]/[file]
* Next to this structure, create a folder called `test`, put a folder called `test` in it and put some svelte files in it e.g. test1, test2: you will see these routes work (e.g. at /test/test/test1)
* But it has to be noted that when you go to `test/test`, you get the route that belongs to, the parameter router, [folder]/[file], whereas one would except it would return a 404.

## Expected result

Return a 404.

**Comment by jakobrosenberg** [comment]
I get you what you mean, but to keep things predictable, I think it's important to stick to a matching pattern with as few exceptions as possible.

Currently it goes like this:
Order the routes by statics, dynamics and fallbacks and use the first match.

Changing this behavior would add complexity and go against the expected behavior for someone wanting to override a dynamic route.

Consider this scenario: You have a shop with the structure ``/[category]/[product].svelte``. It works fine, but you have a few specialty items which don't fit into a template, so you create a static route to handle them, ie. : ``/electronics/flux-capacitator.svelte``.

What you're effectively trying to do, is override a dynamic route, which would require a more specific route. Since a directory is only a path and not a route, you would need to add an ``index.svelte`` or ``_fallback.svelte`` to the folder you want to take precedence.

**Comment by Wolfr** [comment]
If there is good reasoning behind it, I get it, I just thought it was a bug. Having the correct 404 page on a non-dynamic URL is less important than the simplicity of overriding as you describe it.
