### ISSUE TITLE
Stop Scroll reset in nested routes

### ISSUE THREAD

**Issue by yousufiqbal** [roxiness/routify#86]
Currently, In Routify when I browse nested routes the scroll position resets to top. Please add an option to stop scrolling in nested routes like `sapper-noscroll` in sapper.

**Comment by jakobrosenberg** [comment]
@yousufiqbalhashim Sorry, this is undocumented so far, but is actually possible with the ``scroll-lock``.

``<div data-routify="scroll-lock">``

Unlike Sapper, where you have to modify every link, this tag only has to be applied to the element you don't wish to scroll.

Since this is undocumented, it might be a good time to ask if ``routify="scroll-lock"`` would be a better syntax.

**Comment by yousufiqbal** [comment]
Can you please give a baby-step example. I tried the above method but still unable to achieve it :(

**Comment by jakobrosenberg** [comment]
```html
<div data-routify="scroll-lock">
<!-- content you don't want scrolled back to the top -->
</div>
```

For anything more precise, I need an example of what you're trying to accomplish or a repo.

**Comment by yousufiqbal** [comment]
This helped. Thanks

**Comment by jakobrosenberg** [comment]
Happy to help. :)
